### PR TITLE
type alias byte for bytes1

### PR DESCRIPTION
**Pull request by nathanielCherian**
Notes:
- Had to change some of the tests because 'byte' was being used as a variable.
- All tests pass in ```/packages/cashc``` dir, however, they fail from the root. Even on a fresh copy, it still threw errors. 

#59

### CODE REVIEW

**Comment by rkalis** [comment]
Awesome! Thanks for the PR @nathanielCherian, I'll look at it early coming week.

**Comment by rkalis** [comment]
Looks great! I added two more test cases and removed one that was apparently duplicate (unrelated to this PR, but I noticed it along the way).

**Comment by rkalis** [comment]
Oh and the failing tests were because I run some tests on mainnet, and the wallets ran oout of money. Sorry about that!

**Comment by nathanielCherian** [comment]
Great, sounds good!

**Pull request merged**
