### PR TITLE
[feat] - browser support

### PR DESCRIPTION
**Pull request by alcipir**
So, got it done without using webpack, but needs more testing. I'm not entirely sure this approach is working on every example available and would love to have some feedback on this.

- There's a Browser folder in the examples folder now, which is just a create-react-app
- I kept the original .equiv file, but I might add a script to just trim the JS parts from the optimizations.equiv file before running cashproof, let me know what would be the best approach on this.
- If you want to test it out, make sure to run "npm link (inside cashscript folder) and "npm link cashscript (inside the Browser folder) on my fork in order to properly test it.

@rkalis let me know your thoughts on this.

### CODE REVIEW

**Comment by rkalis** [comment]
Awesome! I got it to run on my machine as well. Added `examples/Browser` as a separate workspace in the root package.json so that Lerna automatically links the local version of cashscript into the project without doing `npm link`.

I also figured out how to do the cashproof stuff. I added a `pre` and `post` hook for running the optimisations proof:

```json
"preproof:opt": "cp packages/cashc/src/optimisations/Optimisations.ts opt.equiv && sed -i '' '/`/d' opt.equiv",
"proof:opt": "yarn cashproof opt.equiv",
"postproof:opt": "rm opt.equiv",
```

So now when running `yarn proof:opt` or `yarn proof` it copies over the ts file into a temp file, and cuts out the lines containing \`. Then it executes cashproof on that file and deletes it again.

**Comment by alcipir** [comment]
Cool! Will make these changes and push the commit ASAP.

**Comment by rkalis** [comment]
Did you enable commits from maintainer in your PR? The I'll push my changes so you can pick it up from there

**Comment by alcipir** [comment]
> Did you enable commits from maintainer in your PR? The I'll push my changes so you can pick it up from there

Yes, it's enabled. Let me know if there's any issue with that :)

**Comment by rkalis** [comment]
Welp looks like I messed up pushing my changes 😅

**Comment by rkalis** [comment]
Can you push your changes to your remote again?

**Comment by alcipir** [comment]
done

**Comment by rkalis** [comment]
I'm glad that in the end it was possible to do it without any complex build processes. So we'll have to add a note to the docs stating that CashScript can only be compiled as a string in the web, so they will have to load the file in a different way (like a `GET` request to some file), and then pass in the file contents.

Perhaps we can change the example app so that it has a pre-filled input field for the constructor argument and the function arguments, and it shows the balance/address in the UI. I think that we're all done after that.

**Comment by alcipir** [comment]
Added option to select a network and an input for seed words, what do you think?

**Comment by rkalis** [comment]
I just created the branch `v0.3.2` from master. Can you change the PR to target that branch, then I'll merge it in.

**Comment by alcipir** [comment]
Done!

**Comment by rkalis** [comment]
Perfect. Thanks again for the help.

**Pull request merged**
